export interface MaterialColors {
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  background: string;
  onBackground: string;
  surface: string;
  onSurface: string;
  surfaceVariant: string;
  onSurfaceVariant: string;
  surfaceContainer: string;
  surfaceContainerLow: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  surfaceContainerLowest: string;
  outline: string;
  outlineVariant: string;
  error: string;
  onError: string;
  errorContainer: string;
  onErrorContainer: string;
  inverseSurface: string;
  inverseOnSurface: string;
  inversePrimary: string;
  shadow: string;
  scrim: string;
  statusBar: 'dark' | 'light';
}

export const lightColors: MaterialColors = {
  primary: '#031632',
  onPrimary: '#ffffff',
  primaryContainer: '#1a2b48',
  onPrimaryContainer: '#8293b5',
  secondary: '#775a19',
  onSecondary: '#ffffff',
  secondaryContainer: '#fed488',
  onSecondaryContainer: '#785a1a',
  tertiary: '#0c1728',
  onTertiary: '#ffffff',
  tertiaryContainer: '#212c3d',
  onTertiaryContainer: '#8893a8',
  background: '#f7f9fb',
  onBackground: '#191c1e',
  surface: '#f7f9fb',
  onSurface: '#191c1e',
  surfaceVariant: '#e0e3e5',
  onSurfaceVariant: '#44474d',
  surfaceContainer: '#eceef0',
  surfaceContainerLow: '#f2f4f6',
  surfaceContainerHigh: '#e6e8ea',
  surfaceContainerHighest: '#e0e3e5',
  surfaceContainerLowest: '#ffffff',
  outline: '#75777e',
  outlineVariant: '#c5c6ce',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  inverseSurface: '#2d3133',
  inverseOnSurface: '#eff1f3',
  inversePrimary: '#b6c7eb',
  shadow: '#000000',
  scrim: '#000000',
  statusBar: 'dark',
};

export const darkColors: MaterialColors = {
  primary: '#f2ca50',
  onPrimary: '#3c2f00',
  primaryContainer: '#d4af37',
  onPrimaryContainer: '#554300',
  secondary: '#b6c7eb',
  onSecondary: '#20304e',
  secondaryContainer: '#394968',
  onSecondaryContainer: '#a8b9dd',
  tertiary: '#bed0e7',
  onTertiary: '#203243',
  tertiaryContainer: '#a2b5cb',
  onTertiaryContainer: '#354759',
  background: '#131313',
  onBackground: '#e5e2e1',
  surface: '#131313',
  onSurface: '#e5e2e1',
  surfaceVariant: '#353534',
  onSurfaceVariant: '#d0c5af',
  surfaceContainer: '#201f1f',
  surfaceContainerLow: '#1c1b1b',
  surfaceContainerHigh: '#2a2a2a',
  surfaceContainerHighest: '#353534',
  surfaceContainerLowest: '#0e0e0e',
  outline: '#99907c',
  outlineVariant: '#4d4635',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  inverseSurface: '#e5e2e1',
  inverseOnSurface: '#313030',
  inversePrimary: '#735c00',
  shadow: '#000000',
  scrim: '#000000',
  statusBar: 'light',
};
